### ISSUE TITLE
Round/Clamp decimal values for prices

### ISSUE THREAD

**Issue by Qwiso** [domialex/Sidekick#75] opened 2020-01-11 18:16 UTC
![image](https://user-images.githubusercontent.com/4432563/72208759-a0644d00-3474-11ea-8532-b447a90366ec.png)

**Comment by domialex** [comment] 2020-01-12 14:02
Related to #50.

**Comment by domialex** [comment] 2020-01-18 03:41
Duplicate of #91.

**Closed by domialex** 2020-01-18 03:41 UTC
Labels: duplicate
