### ISSUE TITLE
It just doesn't open

### ISSUE THREAD

**Issue by jsonbrooks** [domialex/Sidekick#373] opened 2020-05-03 01:30 UTC
I've been using this a little while now and all of the sudden it won't open. I've tried restarting and re-downloading the exe and it's always the same thing, nothing. No Windows Bar Icon, nothing obvious in task manager.

**Comment by domialex** [comment] 2020-05-03 01:33
Duplicate of #344. Try to download the 0.8.0 alpha version for now, since 0.8 isn't ready yet.

**Closed by domialex** 2020-05-03 01:33 UTC
