### ISSUE TITLE
Choose which item properties should be included in default search

### ISSUE THREAD

**Issue by Zalhera** [domialex/Sidekick#63] opened 2020-01-10 11:29 UTC
Add option in future setting menu to choose and configure which properties should be included in the default Ctrl + D search.
Examples:
 - Always include influence on equippable items
 - Always include number of white sockets on item
 - etc.

**Comment by domialex** [comment] 2020-01-10 22:55
The settings window would have default values.
The overlay window would, in the future, be able to open a new window to edit/view the current query. Just like POE-TradeMacro has but also able to add/remove attributes.

**Comment by leMicin** [comment] 2020-03-18 23:28
Duplicate of #287 . The solution is slightly different than what was proposed here. It will be explained in #287

**Closed by leMicin** 2020-03-18 23:28 UTC
Labels: Priority: Low, Status: Available, Type: Enhancement
