### ISSUE TITLE
Use ViewModels only in WPF contexts - Reduce static classes usage and move to DI

### ISSUE THREAD

**Issue by onurtnrkl** [domialex/Sidekick#51] opened 2020-01-08 22:21 UTC
The projects architecture makes me confused. There are both controllers and view models. Also there are some views behave like view models. The architectural pattern(MVC, MVVM, ...) should be determined clearly in my opinion. Also, DI solution should be helpful for dependencies instead of static classes.

**Comment by domialex** [comment] 2020-01-08 23:35
The reason why the WPF uses a model instead of a ViewModel for now, is because I still haven't done the ViewModel :D.
I agree with that part.
As for the static classes, it's not popular, but it makes it easier to be thread-safe and makes collaboration easier.
Don't hesitate to refactor to your tastes!

**Comment by leMicin** [comment] 2020-01-14 19:05
Dependency Injection is being implemented with #97 .

Instead of static classes. We will use static services inside the ServiceProvider (Dependency Injection).

I don't know if this issue still needs to be opened as we can move the discussion inside #97

**Comment by domialex** [comment] 2020-01-14 21:49
Duplicate of #97.

**Closed by domialex** 2020-01-14 21:49 UTC
Labels: enhancement
