### ISSUE TITLE
Filter Possibilities

### ISSUE THREAD

**Issue by igorcastroo** [domialex/Sidekick#47] opened 2020-01-08 16:00 UTC
Filter the damage of a weapon, or the HP of an item, iLvL ...

Just like Poe Trade

**Comment by domialex** [comment] 2020-01-08 23:42
Obrigado. This will probably be added indirectly by #8

**Comment by domialex** [comment] 2020-01-19 15:53
Duplicate of #8.

**Closed by domialex** 2020-01-19 15:53 UTC
Labels: enhancement
