### ISSUE TITLE
Open Wiki not working for gems

### ISSUE THREAD

**Issue by Silentguard** [domialex/Sidekick#360] opened 2020-04-24 14:20 UTC
```
2020-04-24 22:19:05.450 +08:00 [INF] Keybind Triggered - Open Wiki
2020-04-24 22:19:05.825 +08:00 [WRN] Unable to open POE Wiki for specified item as it has no name! {"Armor":0,"EnergyShield":0,"Evasion":0,"ChanceToBlock":0,"Quality":23,"GemLevel":21,"MapTier":0,"ItemQuantity":0,"ItemRarity":0,"MonsterPackSize":0,"Blighted":false,"CriticalStrikeChance":0,"AttacksPerSecond":0,"ItemText":"Rarity: Gem\r\nInfernal Blow\r\n--------\r\nAttack, AoE, Melee, Strike, Fire, Duration\r\nLevel: 21 (Max)\r\nMana Cost: 6\r\nEffectiveness of Added Damage: 135%\r\nQuality: +23% (augmented)\r\n--------\r\nRequirements:\r\nLevel: 72\r\nStr: 159\r\n--------\r\nAttacks with your weapon, applying a charged debuff to enemies hit by your strike, and an uncharged debuff to any other enemies hit. Upon reaching 6 charges, expiring, or the enemy's death, the charged debuff is removed, and it deals damage to that and other nearby enemies. Enemies with either debuff explode when they die, damaging other nearby enemies. Damage from this explosion cannot be reflected. Requires a Sword, Axe, Mace, Sceptre, Staff or Unarmed.\r\n--------\r\n50% of Physical Damage Converted to Fire Damage\r\nDeals 134.5% of Base Damage\r\nBase duration is 0.80 seconds\r\n81 to 122 Added Fire Damage\r\nExplosion deals base Fire Damage equal to 6% of the corpse's Maximum Life\r\n11% increased Area of Effect\r\n+3 to Melee Strike Range\r\nDebuff deals 66% of Damage per Charge\r\n--------\r\nPlace into an item socket of the right colour to gain this skill. Right click to remove from a socket.\r\n--------\r\nCorrupted\r\n","Name":null,"TypeLine":"Infernal Blow","Identified":true,"ItemLevel":0,"Rarity":"Gem","Corrupted":true,"Influences":{"Crusader":false,"Elder":false,"Hunter":false,"Redeemer":false,"Shaper":false,"Warlord":false,"$type":"Influences"},"Sockets":[],"Extended":{"Text":null,"Mods":{"Implicit":[],"Explicit":[{"Name":null,"Tier":null,"Magnitudes":[{"Hash":"explicit.stat_280731498","Min":11,"Max":11,"$type":"Magnitude"}],"$type":"Mod"},{"Name":null,"Tier":null,"Magnitudes":[{"Hash":"explicit.stat_1533563525","Min":50,"Max":50,"$type":"Magnitude"}],"$type":"Mod"},{"Name":null,"Tier":null,"Magnitudes":[{"Hash":"explicit.stat_2264295449","Min":3,"Max":3,"$type":"Magnitude"}],"$type":"Mod"}],"Crafted":[],"Enchant":[],"Pseudo":[],"$type":"Mods"},"DamagePerSecond":0,"ElementalDps":0,"PhysicalDps":0,"$type":"Extended"},"$type":"ParsedItem"}
```
Item object.
```
{
  "Armor": 0,
  "EnergyShield": 0,
  "Evasion": 0,
  "ChanceToBlock": 0,
  "Quality": 23,
  "GemLevel": 21,
  "MapTier": 0,
  "ItemQuantity": 0,
  "ItemRarity": 0,
  "MonsterPackSize": 0,
  "Blighted": false,
  "CriticalStrikeChance": 0,
  "AttacksPerSecond": 0,
  "ItemText": "Rarity: GemInfernal Blow--------Attack, AoE, Melee, Strike, Fire, DurationLevel: 21 (Max)Mana Cost: 6Effectiveness of Added Damage: 135%Quality: +23% (augmented)--------Requirements:Level: 72Str: 159--------Attacks with your weapon, applying a charged debuff to enemies hit by your strike, and an uncharged debuff to any other enemies hit. Upon reaching 6 charges, expiring, or the enemy's death, the charged debuff is removed, and it deals damage to that and other nearby enemies. Enemies with either debuff explode when they die, damaging other nearby enemies. Damage from this explosion cannot be reflected. Requires a Sword, Axe, Mace, Sceptre, Staff or Unarmed.--------50% of Physical Damage Converted to Fire DamageDeals 134.5% of Base DamageBase duration is 0.80 seconds81 to 122 Added Fire DamageExplosion deals base Fire Damage equal to 6% of the corpse's Maximum Life11% increased Area of Effect+3 to Melee Strike RangeDebuff deals 66% of Damage per Charge--------Place into an item socket of the right colour to gain this skill. Right click to remove from a socket.--------Corrupted",
  "Name": null,
  "TypeLine": "Infernal Blow",
  "Identified": true,
  "ItemLevel": 0,
  "Rarity": "Gem",
  "Corrupted": true,
  "Influences": {
    "Crusader": false,
    "Elder": false,
    "Hunter": false,
    "Redeemer": false,
    "Shaper": false,
    "Warlord": false,
    "$type": "Influences"
  },
  "Sockets": [],
  "Extended": {
    "Text": null,
    "Mods": {
      "Implicit": [],
      "Explicit": [
        {
          "Name": null,
          "Tier": null,
          "Magnitudes": [
            {
              "Hash": "explicit.stat_280731498",
              "Min": 11,
              "Max": 11,
              "$type": "Magnitude"
            }
          ],
          "$type": "Mod"
        },
        {
          "Name": null,
          "Tier": null,
          "Magnitudes": [
            {
              "Hash": "explicit.stat_1533563525",
              "Min": 50,
              "Max": 50,
              "$type": "Magnitude"
            }
          ],
          "$type": "Mod"
        },
        {
          "Name": null,
          "Tier": null,
          "Magnitudes": [
            {
              "Hash": "explicit.stat_2264295449",
              "Min": 3,
              "Max": 3,
              "$type": "Magnitude"
            }
          ],
          "$type": "Mod"
        }
      ],
      "Crafted": [],
      "Enchant": [],
      "Pseudo": [],
      "$type": "Mods"
    },
    "DamagePerSecond": 0,
    "ElementalDps": 0,
    "PhysicalDps": 0,
    "$type": "Extended"
  },
  "$type": "ParsedItem"
}
```

**Comment by domialex** [comment] 2020-04-24 14:34
Duplicate of #306.

**Closed by domialex** 2020-04-24 14:34 UTC
