### ISSUE TITLE
Option to see items' stats in the listing on hover

### ISSUE THREAD

**Issue by ZzZombo** [domialex/Sidekick#129] opened 2020-01-19 16:20 UTC
* An option to load next page, as well as to return one page back, and a quick link to go the first.
* Option to see items' stats in the listing on hover.
* A button to close the window by mouse.

**Comment by domialex** [comment] 2020-01-19 16:22
- [x] An option to load next page, as well as to return one page back, and a quick link to go the first. #102  
- [ ] Option to see items' stats in the listing on hover.
- [x ] A button to close the window by mouse. Duplicate of #106.

**Comment by domialex** [comment] 2020-01-25 12:54
Can be updated with a real UserControl in the future.

**Closed** 2020-01-25 12:54 UTC
Labels: enhancement
