### ISSUE TITLE
Program Crash

### ISSUE THREAD

**Issue by mabryant** [domialex/Sidekick#376] opened 2020-05-04 22:35 UTC
Program crashes when right clicking on the system tray icon.  Attached is the log file.
[Sidekick_Log20200504.log](https://github.com/domialex/Sidekick/files/4578105/Sidekick_Log20200504.log)

**Comment by domialex** [comment] 2020-05-04 22:41
Duplicate of #344. I'm pretty this is now fixed, you can try to [re-download the latest version](https://github.com/domialex/Sidekick/releases/latest/download/Sidekick.exe).

**Closed by domialex** 2020-05-04 22:41 UTC
