### ISSUE TITLE
Price check filter: "item name"

### ISSUE THREAD

**Issue by LeGorge** [domialex/Sidekick#337] opened 2020-04-02 20:14 UTC
Currently, the name of the item goes in the search, and that narrows the search by a lot
 - Ex: A demon's horn wand goes from 5ex to ~40c when taking the name out in the search

So, put a name filter in the tab properties

**Comment by LeGorge** [comment] 2020-04-02 20:23
I just realize the name is what narrows the item type, but that should go as "item category"

Hum, perhaps there's no way of knowing that a "vaal gauntlets" should be searched as gloves, or that a "demon's horn" is a wand, but this is definitely an issue.

And we could always just map every base type item known to what it actually is... :p

**Comment by Blinke** [comment] 2020-04-03 15:54
I agree that this is a bit of a problem. So far we've tried to rely on the data from the public API as possible but this might warrant an exception. Hard-coding some dictionaries wouldn't take too long by hand and would only have to be updated once per league at most.

**Comment by leMicin** [comment] 2020-06-16 03:35
Closing this as this is a duplicate of #379

**Closed by leMicin** 2020-06-16 03:35 UTC
Labels: Priority: Medium, Status: Available, Type: Enhancement
