### ISSUE TITLE
Add customizable messages? 

### ISSUE THREAD

**Issue by Bannedmyself** [domialex/Sidekick#272] opened 2020-03-15 09:30 UTC
Like 
/oos
Sorry item has been sold
Can you wait one minute? etc...

thanks!

**Comment by domialex** [comment] 2020-03-15 13:15
Duplicate of #85.
It's a feature I wanted to add since the beginning. Something like MercuryTrade and TraderForPoe.

**Closed by domialex** 2020-03-15 13:15 UTC
