### ISSUE TITLE
Crash after startup

### ISSUE THREAD

**Issue by XeperX** [domialex/Sidekick#374] opened 2020-05-04 13:36 UTC
I had used the Sidekick for a week, but 2 days ago it fails to work. The initialization seems to be OK, appears on the tray, but there is no response within the game, checking on the tray I get the following error:
"A fatal error occured and Sidekick is unable to recover. The error has been logged to a log file where Sidekick is installed, please report this error on https://github.com/domialex/Sidekick and attach the logs"
[Sidekick_Log20200504.log](https://github.com/domialex/Sidekick/files/4574919/Sidekick_Log20200504.log)
No virus related alerts/quaranteened objects, had no changes on my PC, it was working without an issue before, but now it crashes 100%
I really liked this tool until it woked, I hope you can resolve this issue :)

**Comment by domialex** [comment] 2020-05-04 14:00
Duplicate of #344. Try to download the [0.8.0 alpha version](https://1drv.ms/u/s!AusbGardZ2xhgZ9lg--2fDEMV6zRQw?e=Q7OI7L) for now, since 0.8 isn't ready yet.
I'm pretty sure I found the bug (it's a .NET bug), so the next official release should fix this!

**Closed by domialex** 2020-05-04 14:00 UTC
